name: mlz_jwst
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.9
  
  # Core Scientific Computing
  - numpy>=1.20.0
  - scipy>=1.7.0
  
  # Astronomy
  - astropy>=5.0.0
  
  # Machine Learning
  - scikit-learn>=1.0.0
  
  # Visualization
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  
  # Jupyter
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - ipython>=7.0.0
  
  # Utilities
  - pyyaml>=5.4.0
  - tqdm>=4.60.0
  
  # Pip-only packages
  - pip
  - pip:
    - dustmaps>=1.0.0
    - urllib3>=1.26.0
    - gpz_pype>=0.1.0
    - eazy-py>=0.5.0
